version: '3'

services:
  db:
    image: mysql:8.0.26
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/volume:/var/lib/mysql
      - ./mysql/script:/docker-entrypoint-initdb.d
    environment:
     - MYSQL_ROOT_PASSWORD=root
    networks:
      - network
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    command: node index.js
    image: marciovsantos/node:prod
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - network
    #volumes:
    #  - ./node/:/usr/src/app
    depends_on:
      - db
  web: 
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: marciovsantos/nginx:prod
    container_name: web
    networks:
      - network
    ports:
      - 8080:80
    depends_on:
      - app      
networks:
  network:
   driver: bridge